### ISSUE TITLE
huhIssue

### ISSUE THREAD

**Issue by tanasegabriel** [tanasegabriel/testRepo#79]

**Comment by randomuser23** [comment]
### Should this issue have a Status Page update?
#### Hey, you tagged this issue as P0 or P1, so we wanted to ask if you need to update the status page
- [ ] **Yes** - if selected, we will page some folks in CS who will work with you to update the status page. We will also add some tags for tracking incidents
- [ ] **No** - if selected, nothing will happen
- [ ] **I'm not sure** - if selected, we will page some CS folks who can help figure out if we should update the status page

**Comment by randomuser23** [comment]
### Do you need an Incident Commander?
#### Because this was tagged with P1 or P0, we want to check if you need a commander. You can always page one directly [here](https://intercomrades.intercom.com/admin/pagers), and see the guidelines [here](https://www.notion.so/intercomrades/Incident-Commanders-3dcc4a31b8404c59900730e742fc436a). It’s totally fine if you dont need a commander too!
- [ ] **Yes** -  if selected, we will page an incident commander
- [ ] **No** - if selected, nothing will happen
- [ ] **I'm not sure** - if selected, we’ll notify the commander channel, but a commander will not be paged. Be sure to check out our guidelines [here](https://www.notion.so/intercomrades/Incident-Commanders-3dcc4a31b8404c59900730e742fc436a). You can always change your answer to yes or page directly if you change your mind

**Comment by randomuser23** [comment]
We’ve asked someone in CS to take a look

**Comment by randomuser23** [comment]
We have paged a commander for you

**Comment by tanasegabriel** [comment]
aha

**Comment by tanasegabriel** [comment]
nooo
